### ISSUE TITLE
v1.0.0 release

### ISSUE THREAD

**Issue by robinpoort** [timble/kodekit-ui#33]
Work on a v1.0.0 release.

- [x] middlepane resize cookie width earlier in JS to avoid jump (and set with `<style></style>` on stopdrag instead of using style="")
- [x] disable table click to open functionality by adding `k-js-click-to-select` class to the `<table>`
- [x] Make menus and dragger available on AJAx (or reload them)
- [x] 3column layout
- [x] more flexible toggle menus (using `[data-content]` for button content.)
- [x] Separate the UI JS code from the rest
- [x] rewrite and improve touch swipe menus
- [x] refactor `layout/_top.scss`
- [x] improve scrolltab (make more standalone and fix when clicking)
- [x] swipe menus classname refactor (is-open etc.). Each has it's own name now
- [x] make possible to open left menu when right pane (in three pane layout) is open? Button is visible so it would be good to have it able to open
- [x] flexbox form view with flexing wisywig (see: https://github.com/joomlatools/textman/issues/475)
- [x] Put everything into 4pixel grid
- [x] refactor all `.k-is-open` etc. classes to variable
- [x] replace JS grid with inline-block(+js) > flexbox (+js) > CSS grid (no-js) system
- [x] refactor button mixin (using class variables instead of k-is-open, check usage of `.badge` etc.)
- [x] update normalize.css to 7.0.0
- [x] mobile touchslide menu back in shows two active overlays? Very dark when sliding back (using touch)
- [x] rename `.k-off-canvas-menu-toggle-holder` to `.k-off-canvas-toggle-holder` and `.k-off-canvas-menu-toggle` to `.k-off-canvas-toggle`
- [x] new folder structure for SCSS
- [x] rename menu-container to top? (not always a menu)
- [x] remove flexbox > table fallback, it's 2018, cmon
- [x] rename `$k-btn` to `$k-button`
- [x] refactor `$k-variables` in mixins to unprefixed since they're local
- [x] refactor variable names. All should be built-up the same 
- [x] cleanup unused styleguide code, living on joomlatools.com now
- [x] remove k-title-bar--dark and k-title-bar--inline
- [x] Get rid of `@import "molecules` etc. and import separate files in `_core.scss`
- [x] add variables to include atoms, molecule etc. upon building

Variable names building:
```scss
$k-[molecule]-[modifier]-[child]-[type]-[state]-[style]: ... !default;

1. [molecule]: Name or short-name for the molecule / element you are styling
2. [modifier]: Does the molecule / element have a modifier? Place it second
3. [child]: just one level deep. distinguishing `$k-navigation-border` from `$k-naviagtion-item-border` and `$k-navigation-lin-border'
4. [type]: for example `small`, `big`, `bold`,  `class` etc.
5. [state]: States like `active`, `disabled` etc.
6. [style]: Name of the CSS style for example `background-image`, `line-height`, `z-indez` etc.

// examples

// [style] (for base variables)
$k-font-weight: bold !default 

// ([state])[type] (for base variables)
$k-active-class: .active !default;

// [type]-[style]
$k-small-line-height: 12px !default;

// [molecule]
$k-navigation: true !default;

// [molecule]-[style]
$k-navigation-background: white !default;

// [molecule]-[modifier]
$k-navigation-round: true !default;

// [molecule]-[modifier]-[style]
$k-navigation-round-border-radius: 4px !default;

// [molecule]-[child]-[style]
$k-navigation-item-background: white !default;

// [molecule]-[child]-[state]-[style]
$k-navigation-item-hover-background: white !default;

// [molecule]-[child]-[state]-[type]
$k-navigation-item-active-class: $k-active-class !default;

// [molecule]-[child]-[type]-[state]-[style]
$k-navigation-item-small-hover-background: grey !default;

// [molecule]-[modifier]-[child]-[type]-[state]-[style]
$k-navigation-round-item-small-hover-background: grey !default;

```

# Todo after release:

- Rebuild `fileman/code/administrator/components/com_fileman/views/filelink/tmpl/upload.html.php`
- Adjust and check docman, fileman, logman and textman views
